### ISSUE TITLE
How to start new app inside kiosk mode ?

### ISSUE THREAD

**Issue by Harin-Kaklotar** [mrugacz95/kiosk#1]
Hi @mrugacz95 thanks for this awesome example. I have one question. If we are upload this app to google play store then how user skip that **adding google account step** ??
So how do the normal user use this app whit play store account ?
Suppose I have run this application on the android emulator then how do I start new app ? means how do I **open any app inside kiosk mode** ?

**Comment by mrugacz95** [comment]
Hi,
It is not possible to run every app with kiosk mode due the security reasons. With device owner app is able to change password policies, lock device or even wipe whole data. It would be dangerous to let any app doing it. This solution is mostly created for kiosks and devices to which you have access and which you are able to configure. So without admin permission all you can achieve is full screen mode and lock task, unless user would manually configure your app as device owner.
