### ISSUE TITLE
Flutter example?

### ISSUE THREAD

**Issue by fabioselau077** [mrugacz95/kiosk#10]
Hi, do you have any examples of how to implement this with Flutter? I'm talking about calling native Android code through Flutter...

**Comment by mrugacz95** [comment]
Quick search gives me this tutorial for calling native code from Flutter: https://medium.com/@vinubalagopalap/using-method-channels-to-call-native-android-code-from-flutter-33c78fdef4a4. But Your issue is not directly elated with my kiosk example so let me close it.
