### ISSUE TITLE
How to install update from own server?

### ISSUE THREAD

**Issue by Mura75** [mrugacz95/kiosk#2]
Hi! @mrugacz95 
Thank you for the great [articles](https://snow.dog/blog/kiosk-mode-android) and this code example. I have a question about updating the app from my own server. I don't find the last part of the app update at your articles.

**Comment by mrugacz95** [comment]
There is no simple answer as there are many way to implement this. 
You can find some info [here](https://sureshjoshi.com/mobile/updating-android-kiosk-app)
And I have also add example code for app installation [here](https://github.com/mrugacz95/kiosk/blob/master/app/src/main/java/pl/mrugacz95/kiosk/MainActivity.kt#L184).
